CLASS zbp_arete_dbs_dd_company_001 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zarete_dbs_dd_company_001.
protected section.
private section.
ENDCLASS.



CLASS ZBP_ARETE_DBS_DD_COMPANY_001 IMPLEMENTATION.
ENDCLASS.
