CLASS zbp_arete_dbs_dd_bank_001 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zarete_dbs_dd_bank_001.
protected section.
private section.
ENDCLASS.



CLASS ZBP_ARETE_DBS_DD_BANK_001 IMPLEMENTATION.
ENDCLASS.
