CLASS zbp_arete_dbs_dd_t017 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zarete_dbs_dd_t017.
protected section.
private section.
ENDCLASS.



CLASS ZBP_ARETE_DBS_DD_T017 IMPLEMENTATION.
ENDCLASS.
